import { describe, expect, test } from 'vitest'
import { sandbox } from '../_cli_helper.ts'

describe('[ki --help]', () => {
  test('prints root and nested command help through universal --help', async () => {
    const box = await sandbox()
    const root = await box.run('ki')
    const help = await box.run('ki --help')
    const management = await box.run('ki manage --help')
    const nested = await box.run('ki acquire chatgpt import --help')
    const list = await box.run('ki manage list --help')
    const install = await box.run('ki harness install --help')
    const reinstall = await box.run('ki harness reinstall --help')
    const uninstall = await box.run('ki harness uninstall --help')
    const update = await box.run('ki manage update --help')
    const upgrade = await box.run('ki repo upgrade --help')
    const roadmapRoot = await box.run('ki repo roadmap --help')
    const roadmap = await box.run('ki repo roadmap list --help')
    const roadmapPrune = await box.run('ki repo roadmap prune --help')
    const roadmapPromote = await box.run('ki repo roadmap promote --help')
    const roadmapDemote = await box.run('ki repo roadmap demote --help')
    const repository = await box.run('ki repo --help')
    const localSet = await box.run('ki dev local set --help')
    const localOn = await box.run('ki dev local on --help')
    const localOff = await box.run('ki dev local off --help')
    const agora = await box.run('ki agora --help')
    const agoraOpen = await box.run('ki agora open --help')
    const retiredWorkspace = await box.run('ki workspace --help')
    const missing = await box.run('ki manage missing --help')
    const search = await box.run('ki manage search --help')
    const cleanup = await box.run('ki manage cleanup --help')
    const docs = await box.run('ki manage docs --help')
    const repair = await box.run('ki manage repair --help')

    expect(root.output).toContain('Usage: ki')
    expect(help.exitCode).toBe(0)
    expect(help.output).toContain('acquire')
    expect(help.output).toContain('manage')
    expect(management.output).toContain('docs')
    expect(management.output).toContain('search')
    expect(management.output).toContain('list')
    expect(nested.exitCode).toBe(0)
    expect(list.output).toContain('list installed harness capabilities and declared skills')
    expect(install.output).toContain('configured compatible harness')
    expect(reinstall.output).toContain('inactive installed harness')
    expect(uninstall.output).toContain('installed non-canonical harness')
    expect(update.output).toContain('installer-managed CLI')
    expect(upgrade.output).toContain('one or more KI repositories')
    expect(roadmapRoot.output).toContain('inspect and mechanically maintain governed work items')
    expect(roadmap.output).toContain('list governed work items')
    expect(roadmapPrune.output).toContain('delete completed governed work items')
    expect(roadmapPrune.output).toContain('[id]')
    expect(roadmapPromote.output).toContain('move one work item toward now')
    expect(roadmapDemote.output).toContain('move one work item toward future')
    expect(missing.output).toContain('report desired capabilities without an installed provider')
    expect(search.output).toContain('search verified installed harness capabilities')
    expect(cleanup.output).toContain('report eligible KI-managed stale state')
    expect(docs.output).toContain('print canonical KI documentation locations')
    expect(repair.output).toContain('reconcile configured KI-managed user skill projections')
    expect(repository.output).toContain('educate')
    expect(repository.output).toContain('repair')
    expect(localSet.output).toContain('validate and remember a checkout for one installed harness')
    expect(localOn.output).toContain('Usage: ki dev local on [options] [harness-id]')
    expect(localOn.output).toContain('every configured harness')
    expect(localOff.output).toContain('Usage: ki dev local off [options] [harness-id]')
    expect(localOff.output).toContain('every configured harness')
    expect(agora.output).toContain('resolve declared named Agoras and the registered estate')
    expect(agora.output).toContain('write resolved Agora roots for machine consumption')
    expect(agora.output).toContain('open one Agora through an explicit local target')
    expect(agoraOpen.output).toContain('(choices: "zed", "vscode")')
    expect(retiredWorkspace.exitCode).toBe(2)
  })
})
