import { describe, expect, test } from 'vitest'
import { sandbox } from '../_cli_helper.ts'

describe('[ki --help]', () => {
  test('resolves general and nested help paths without invoking commands', async () => {
    const box = await sandbox()
    expect(await box.run('ki help')).toEqual(await box.run('ki --help'))
    expect(await box.run('ki help harness install')).toEqual(await box.run('ki harness install --help'))
    const unknown = await box.run('ki help harness unknown')
    expect(unknown.exitCode).toBe(2)
    expect(unknown.output).toContain('unknown help topic: harness unknown')
  })
  test('prints root and nested command help through universal --help', async () => {
    const box = await sandbox()
    const root = await box.run('ki')
    const help = await box.run('ki --help')
    const management = await box.run('ki harness --help')
    const nested = await box.run('ki acquire import --help')
    const list = await box.run('ki inventory --help')
    const install = await box.run('ki harness install --help')
    const reinstall = await box.run('ki harness reinstall --help')
    const uninstall = await box.run('ki harness uninstall --help')
    const update = await box.run('ki update --help')
    const upgrade = await box.run('ki repo upgrade --help')
    const roadmapRoot = await box.run('ki repo roadmap --help')
    const roadmap = await box.run('ki repo roadmap list --help')
    const roadmapPrune = await box.run('ki repo roadmap prune --help')
    const roadmapPromote = await box.run('ki repo roadmap promote --help')
    const roadmapDemote = await box.run('ki repo roadmap demote --help')
    const repository = await box.run('ki repo --help')
    const localSet = await box.run('ki dev local set --help')
    const localOn = await box.run('ki dev local on --help')
    const localOff = await box.run('ki dev local off --help')
    const territory = await box.run('ki territory --help')
    const territoryAudit = await box.run('ki territory audit --help')
    const territoryInspect = await box.run('ki territory inspect --help')
    const territoryOpen = await box.run('ki territory open --help')
    const vscode = await box.run('ki vscode --help')
    const missing = await box.run('ki harness missing --help')
    const search = await box.run('ki harness search --help')
    const cleanup = await box.run('ki cleanup --help')
    const docs = await box.run('ki docs --help')
    const repair = await box.run('ki repair --help')

    expect(root.output).toContain('Usage: ki')
    expect(help.exitCode).toBe(0)
    expect(help.output).toContain('acquire')
    expect(help.output).not.toMatch(/^ {2}manage /m)
    expect(help.output).toContain('docs')
    expect(management.output).toContain('search')
    expect(management.output).toContain('list')
    expect(nested.exitCode).toBe(0)
    expect(list.output).toContain('list installed harness capabilities and declared skills')
    expect(install.output).toContain('configured compatible harness')
    expect(reinstall.output).toContain('inactive installed harness')
    expect(uninstall.output).toContain('installed non-canonical harness')
    expect(update.output).toContain('installer-managed CLI')
    expect(upgrade.output).toContain('one or more KI repositories')
    expect(roadmapRoot.output).toContain('inspect and mechanically maintain governed work items')
    expect(roadmap.output).toContain('list governed work items')
    expect(roadmapPrune.output).toContain('delete done or cancelled governed work items')
    expect(roadmapPrune.output).toContain('[id]')
    expect(roadmapPromote.output).toContain('move one work item toward now')
    expect(roadmapDemote.output).toContain('move one work item toward hold')
    expect(missing.output).toContain('report desired capabilities without an installed provider')
    expect(search.output).toContain('search verified installed harness capabilities')
    expect(cleanup.output).toContain('report eligible KI-managed stale state')
    expect(docs.output).toContain('print canonical KI documentation locations')
    expect(repair.output).toContain('repair user skill links and recognised legacy configuration metadata')
    expect(repository.output).toContain('educate')
    expect(repository.output).toContain('repair')
    expect(localSet.output).toContain('validate and remember a checkout for one installed harness')
    expect(localOn.output).toContain('Usage: ki dev local on [options] [harness-id]')
    expect(localOn.output).toContain('every configured harness')
    expect(localOff.output).toContain('Usage: ki dev local off [options] [harness-id]')
    expect(localOff.output).toContain('every configured harness')
    expect(territory.output).toContain('discover and select territories from their Capitals')
    expect(territory.output).toContain('write selected physical roots for machine consumption')
    expect(territory.output).toContain('validate a selected territory or estate')
    expect(territory.output).toContain('inspect one local editor projection for Territory drift')
    expect(territory.output).toContain('open selected repositories in a local target')
    expect(territoryAudit.output).toContain('Usage: ki territory audit [options]')
    expect(territoryInspect.output).toContain('Usage: ki territory inspect [options]')
    expect(territoryInspect.output).toContain('(choices: "zed", "vscode")')
    expect(territoryInspect.output).toContain('--workspace <selector>')
    expect(territoryOpen.output.replace(/\s+/g, ' ')).toContain('(choices: "zed", "vscode", "delta")')
    expect(vscode.output).toContain('reconcile local VS Code projections with the KI registry')
  })
})
