import { describe, expect, test } from 'vitest'
import { sandbox } from './_cli_helper.ts'

describe('[ki help]', () => {
  test('prints the root usage, --help, and nested and unknown-help command interfaces', async () => {
    const box = await sandbox()
    const root = await box.run('ki')
    const help = await box.run('ki --help')
    const nested = await box.run('ki help acquire chatgpt import')
    const list = await box.run('ki help list')
    const install = await box.run('ki help harness install')
    const reinstall = await box.run('ki help harness reinstall')
    const uninstall = await box.run('ki help harness uninstall')
    const update = await box.run('ki help update')
    const upgrade = await box.run('ki help repo upgrade')
    const repository = await box.run('ki repo --help')
    const localSet = await box.run('ki help dev local set')
    const localOn = await box.run('ki help dev local on')
    const missing = await box.run('ki help missing')
    const search = await box.run('ki help search')
    const cleanup = await box.run('ki help cleanup')
    const docs = await box.run('ki help docs')
    const unknown = await box.run('ki help absent')

    expect(root.output).toContain('Usage: ki')
    expect(help.exitCode).toBe(0)
    expect(help.output).toContain('acquire')
    expect(help.output).toContain('cleanup')
    expect(help.output).toContain('docs')
    expect(help.output).toContain('search')
    expect(nested.exitCode).toBe(0)
    expect(list.output).toContain('list installed harness capabilities and declared skills')
    expect(install.output).toContain('configured compatible harness')
    expect(reinstall.output).toContain('inactive installed harness')
    expect(uninstall.output).toContain('installed non-canonical harness')
    expect(update.output).toContain('installer-managed CLI')
    expect(upgrade.output).toContain('one or more KI repositories')
    expect(missing.output).toContain('report desired capabilities without an installed provider')
    expect(search.output).toContain('search verified installed harness capabilities')
    expect(cleanup.output).toContain('report eligible KI-managed stale state')
    expect(docs.output).toContain('print canonical KI documentation locations')
    expect(repository.output).toContain('educate')
    expect(localSet.output).toContain('validate and remember a local harness checkout')
    expect(localOn.output).toContain('configured local harness checkout')
    expect(unknown).toEqual({ exitCode: 2, output: 'ki: error: unknown help topic: absent\n' })
  })
})
