import { describe, expect, test } from 'vitest'
import { sandbox } from './_cli_helper.ts'

describe('[ki --help]', () => {
  test('prints root and nested command help through universal --help', async () => {
    const box = await sandbox()
    const root = await box.run('ki')
    const help = await box.run('ki --help')
    const management = await box.run('ki manage --help')
    const nested = await box.run('ki acquire chatgpt import --help')
    const list = await box.run('ki manage list --help')
    const install = await box.run('ki harness install --help')
    const reinstall = await box.run('ki harness reinstall --help')
    const uninstall = await box.run('ki harness uninstall --help')
    const update = await box.run('ki manage update --help')
    const upgrade = await box.run('ki repo upgrade --help')
    const plan = await box.run('ki repo plan list --help')
    const repository = await box.run('ki repo --help')
    const localSet = await box.run('ki dev local set --help')
    const localOn = await box.run('ki dev local on --help')
    const workspace = await box.run('ki workspace --help')
    const missing = await box.run('ki manage missing --help')
    const search = await box.run('ki manage search --help')
    const cleanup = await box.run('ki manage cleanup --help')
    const docs = await box.run('ki manage docs --help')

    expect(root.output).toContain('Usage: ki')
    expect(help.exitCode).toBe(0)
    expect(help.output).toContain('acquire')
    expect(help.output).toContain('manage')
    expect(management.output).toContain('docs')
    expect(management.output).toContain('search')
    expect(management.output).toContain('list')
    expect(nested.exitCode).toBe(0)
    expect(list.output).toContain('list installed harness capabilities and declared skills')
    expect(install.output).toContain('configured compatible harness')
    expect(reinstall.output).toContain('inactive installed harness')
    expect(uninstall.output).toContain('installed non-canonical harness')
    expect(update.output).toContain('installer-managed CLI')
    expect(upgrade.output).toContain('one or more KI repositories')
    expect(plan.output).toContain('list governed work items')
    expect(missing.output).toContain('report desired capabilities without an installed provider')
    expect(search.output).toContain('search verified installed harness capabilities')
    expect(cleanup.output).toContain('report eligible KI-managed stale state')
    expect(docs.output).toContain('print canonical KI documentation locations')
    expect(repository.output).toContain('educate')
    expect(repository.output).toContain('repair')
    expect(localSet.output).toContain('validate and remember a local harness checkout')
    expect(localOn.output).toContain('configured local harness checkout')
    expect(workspace.output).toContain('manage KI repository workspace groups')
  })
})
